apiVersion: v1
kind: Service
metadata:
  name: photo-blog-node-port
spec:
  type: NodePort
  selector:
    app: photo-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31800
